apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-08-30T17:30:57Z"
  name: my-vm
  uid: 599615df99804ae8
spec:
  cpus: 2
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 800MB
  network: {}
  ssh: true
  storage: {}
status:
  image:
    id: oci://docker.io/weaveworks/ignite-ubuntu@sha256:ad984fa5f6f2db55a0a48860d263a02a0f77aee3bbefa0d71648b4bc287ac13c
    size: 231256502B
  kernel:
    id: oci://docker.io/weaveworks/ignite-kernel@sha256:18ee1005bb3881faf09059038eca8b298d9d7598cde675c4a900e275fe0a2454
    size: 51377512B
  running: false
