apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-08-30T17:30:57Z"
  name: my-vm
  uid: 599615df99804ae8
spec:
  cpus: 2
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 800MB
  network: {}
  ssh: true
  storage: {}
status:
  running: true
